### ISSUE TITLE
start_reading not defined

### ISSUE THREAD

**Issue by cortner** [Keno/TerminalExtensions.jl#12]
I just installed TerminalExtensions, and got the following error message. Prior to that, I simply installed the package and then added `atreplinit((_)->require(:TerminalExtensions))` to my `.juliarc.jl` as described, and restarted julia.

Christoph

$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc1 (2015-09-09 16:07 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

ERROR (unhandled task failure): UndefVarError: start_reading not defined
 [inlined code] from /Users/ortner/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:201
 in anonymous at task.jl:448

**Comment by mbauman** [comment]
Try `pkg.checkout("TerminalExtensions")`.  This was fixed in #8, but a new version hasn't been tagged yet.

**Comment by cortner** [comment]
I now get

$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc1 (2015-09-09 16:07 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

LoadError("/Users/ortner/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl",237,InitError(:TerminalExtensions,ErrorException("Timed out!")))

**Comment by cortner** [comment]
I now get

$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc1 (2015-09-09 16:07 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

LoadError("/Users/ortner/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl",237,InitError(:TerminalExtensions,ErrorException("Timed out!")))

**Comment by mbauman** [comment]
Now that looks like you're not using a new-enough iTerm.  I'm not sure what the status is on what constitutes new enough; I have been using the nightly (currently 2.9.20150812-nightly), but it may work with a beta or recent release.

**Comment by cortner** [comment]
You were right, it works with the latest beta. Thank you!
Christoph
