### ISSUE TITLE
Broken in julia 0.4.2?

### ISSUE THREAD

**Issue by djoshea** [Keno/TerminalExtensions.jl#14]
Hi there, would love to use the figure cat in iTerm but this doesn't seem to work for me on Julia 0.4.2. Error is:

```
julia> using TerminalExtensions
...
ERROR (unhandled task failure): UndefVarError: start_reading not defined
 [inlined code] from /Users/me/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:201
 in anonymous at task.jl:447
```

Might this be related to https://github.com/JuliaLang/julia/issues/1925 ?

There's also a bunch of warnings about `WARNING: Base.Uint8 is deprecated, use UInt8 instead.` but I assume that's unrelated. (I'm very new to Julia so I'm not really sure how to address this.)

**Comment by cmcbride** [comment]
@Keno Just a bump on this as I still get this error on v0.4.6 with the tagged v0.0.2 version.

`julia> Pkg.add("TerminalExtensions")
INFO: Installing TerminalExtensions v0.0.2
INFO: Package database updated

julia> using TerminalExtensions
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:153
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:153
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:153
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
in queryTermcap at /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl

ERROR (unhandled task failure): UndefVarError: start_reading not defined
 [inlined code] from /Users/cmcbride/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:201
 in anonymous at task.jl:447`

**Comment by Keno** [comment]
Can you see if 3b942d4b7a7a54139bd89b890d3acf01ef16136a works on 0.4? If so I can tag that.

**Comment by cmcbride** [comment]
Seems to! `using TerminalExtensions` had no warnings or errors.

I got an inline plot to show using the pyplot backend in 0.4.6 after using TerminalExensions without doing anything else.
