### ISSUE TITLE
using TerminalExtensions causes iTerm2 to become unresponsive

### ISSUE THREAD

**Issue by JonathanAnderson** [Keno/TerminalExtensions.jl#16]
I wanted to give this tool a try now that iTerm2 terminal extensions are in the wild. I pulled and built julia this morning and on the latest commit. I also checked-out `Compat` and `TerminalExtensions` to make sure I was on their latest commit as well. Compat is at [546eccb](https://github.com/JuliaLang/Compat.jl/tree/546eccbeac2ffe3f80ac4854b7d02e853ead2565) and TerminalExtensions is at [1402947](https://github.com/Keno/TerminalExtensions.jl/tree/140294719fb4b03bf83a969157d198193987ecba). ITerm2 is Build 3.0.2.

I don't know how to give more debug assistance or how to further assist this issue since `using TerminalExtensions` causes my terminal to become unresponsive.

![screen shot 2016-06-16 at 3 00 00 pm](https://cloud.githubusercontent.com/assets/1015760/16131358/6f48c296-33d3-11e6-9e76-20e0d9fa8c31.png)

**Comment by Keno** [comment]
I think what can happen is that if julia crashes while iterm is in a proprietary escape sequence, it'll wait for the sequence to finish, which of course never happens.

**Comment by Keno** [comment]
This was fixed in iterm. There'll now be an option to abort if you press ^C.
