### ISSUE TITLE
Text is sometimes (but not always) displayed on 0.6 with PyPlot figures

### ISSUE THREAD

**Issue by omalled** [Keno/TerminalExtensions.jl#31]
The following code produces a bunch of text with julia 0.6.0, iTerm2 3.0.15, and the latest master of TerminalExtensions (f0d8a52828ee4ea6a0f70f5c697167fa9c676e0f).

```
import TerminalExtensions
import PyPlot
fig, ax = PyPlot.subplots()
ax[:plot]([1, 2, 3, 4, 5])
display(fig); println()
display(fig); println()
PyPlot.close(fig)
```

The first `display(fig)` produces text like this (the text is truncated):
```
iVBORw0KGgoAAAANSUhEUgAAAicAAAGgCAYAAABxDccgAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPYQAAD2EBqD+naQAAIABJREFUeJzs3Xl8FIX9//HX5g4hWc4kQAKCARKOXHgQPPBAERCJKGDi70tb0W8PLkWpQq1WsYYWUbmKWr8V2xoQUEERRcQCIlCFJJBw3wlHwpndHGST7M7vD7/ftFhANiSZzeb9fDzm8egOM5n3Wsy8nc/MrsUwDAMRERERD+FjdgARERGRf6dyIiIiIh5F5UREREQ8isqJiIiIeBSVExEREfEoKiciIiLiUVRORERExKOonIiIiIhHUTkRERERj6JyIiIiIh5F5UREREQ8ip/ZAa6Ey+Xi+PHjhIaGYrFYzI4jIiIiV8AwDEpKSmjfvj0+Pld+PaRRlJPjx48THR1tdgwRERGphYKCAqKioq54+0...
```

The second `display(fig)` displays the figure. This describes the behavior if you open a julia REPL and run that code line by line. If you put it in a file and `include("filename.jl")`, the behavior is a bit different. The first time you `include` it, text is displayed twice and no figures are displayed. On subsequent `include`s, the figure is displayed twice.

**Comment by Keno** [comment]
I made a couple of fixes to this to make it more robust if the conversion to image throws or prints deprecation warnings (which was a common cause of this). Let me know if this issue re-occurs.
