### ISSUE TITLE
Change `.juliarc.jl` to `~/.julia/config/startup.jl` in README?

### ISSUE THREAD

**Issue by DilumAluthge** [Keno/TerminalExtensions.jl#43]
Currently, the README says:
> Simply put `atreplinit((_)->Base.require(:TerminalExtensions))` in your `.juliarc.jl` and everything should be detected and configured automatically.

Should it instead say this?
> Simply put `atreplinit((_)->Base.require(:TerminalExtensions))` in your `~/.julia/config/startup.jl` and everything should be detected and configured automatically.

**Comment by Keno** [comment]
probably
